chore(prometheus):
dsaidgovsg/terraform-modules pull request #300
Opened 2024-11-07 10:18 UTC by Tingweiftw

# Story
https://www.notion.so/aipf-locus/Unsafe-Deserialization-1134e47c1d87808792d1eaaff7471966?pvs=4

# What Changed
* Changed prometheus from a submodule to a directory since it is being archived already (https://github.com/cloudalchemy/ansible-prometheus/tree/2201713a60fa4b215c6b15b76c891e32d454d6e2)
* Use `yaml.safe_load` instead of `yaml.load` so that the deserialisation is safe.

2024-11-07 10:18 UTC, Tingweiftw commented on roles/prometheus/molecule/default/tests/test_default.py
> +        return yaml.safe_load(stream)
this is the actual change, the rest are just files been added to the repository

2024-11-08 08:22 UTC, Tingweiftw commented on roles/prometheus/molecule/default/tests/test_default.py
> +        return yaml.safe_load(stream)
outdated, we are removing this submodule since we do not use this submodule for our prometheus setup in l-cloud-gcc

2024-11-09 04:44 UTC, abby-ng commented
did a quick check. `l-cloud-gcc` doesn’t use the `prometheus` module from `terraform-modules` which uses the `roles/prometheus` submodule. It is ok to remove but I would suggest to remove the whole `terraform-modules/modules/prometheus` including the `roles/prometheus` submodule instead of just the role submodule alone. This is because `terraform-modules` is a public repo, removing the role submodule alone will make the whole `prometheus` module incomplete & unusable. We are unsure if anyone using it & it is not obvious if it encounters errors due to this missing role submodule 🙏

2024-11-09 04:45 UTC, abby-ng requested changes
did a quick check. `l-cloud-gcc` doesn’t use the `prometheus` module from `terraform-modules` which uses the `roles/prometheus` submodule. It is ok to remove but I would suggest to remove the whole `terraform-modules/modules/prometheus` including the `roles/prometheus` submodule instead of just the role submodule alone. This is because `terraform-modules` is a public repo, removing the role submodule alone will make the whole `prometheus` module incomplete & unusable. We are unsure if anyone using it & it is not obvious if it encounters errors due to this missing role submodule 🙏

2024-11-11 03:34 UTC, abby-ng requested changes
Looks good! Please remove all the references to prometheus (just some remaining mainly in grafana, telegraf & traefik modules) 🙏

2024-11-11 05:34 UTC, Tingweiftw commented
For the remaining reference, there is no need to remove as they are independent from the prometheus module (can see that no outputs from prometheus module is reference in the other modules) the remaining reference are variables for users to link up their prometheus client based on the address / port / nomad consul names which are not reliant on the module, so I would rather not remove them

2024-11-11 06:16 UTC, abby-ng approved these changes

2024-11-11 07:23 UTC, merged